#define WIFI_SSID "WIFISSID"
#define WIFI_PASS "WIFIPASS"
#define WIFI_PRINT_INTERVAL 500

#define MQTT_BROKER "BROKER IP"
#define MQTT_PORT 1833  

#define AWAKE_TIMEOUT 20000

#define DHT_PIN 2
#define DHT_TYPE DHT22
#define DHT_PWR_PIN 3 // Override PIN3 Serial RX
#define DHT_DISABLE 1000
#define DHT_INTERVAL 2000
